#ifndef AM3_BOARD_GENERIC_H_
#define AM3_BOARD_GENERIC_H_

#include "am3_board.h"

#define ADC_SENSOR_COUNT		ADC_HEIGHT_SENSOR_COUNT * ADC_WIDTH_SENSOR_COUNT
//#define ZIP_BUFFER_SIZE         2*(ADC_SENSOR_COUNT+ADC_HEIGHT_SENSOR_COUNT+1)+4+4+4
#define ZIP_BUFFER_SIZE         4096+24

#ifdef HAS_USB_COMMUNICATION
#define RX_USB_ENDPOINT_CONTROL						0x02

#define TX_USB_ENDPOINT_CONTROL						0x81
#define TX_USB_ENDPOINT_MEASURE_1					0x83
#define TX_USB_ENDPOINT_MEASURE_2					0x85
#define TX_USB_ENDPOINT_MEASURE_3                   0x84

#ifdef USE_USB_1_0
#define USB_BULK_SIZE		0x40
#define BCD_USB				0x0110
#endif

#ifdef USE_USB_2_0
  #define USB_BULK_SIZE		0x0040
  #define BCD_USB			0x0200
#endif

#endif

#ifdef TX_MEASURE_CHANNEL_NUMBER
    #define USB_TX_ENDPOINTS_NUMBER                 TX_MEASURE_CHANNEL_NUMBER
#endif

#if USB_TX_ENDPOINTS_NUMBER > 4
    #define USB_ENDPOINT_PORTS                      { TX_USB_ENDPOINT_CONTROL & 0x3F,TX_USB_ENDPOINT_MEASURE_1 & 0x3F,TX_USB_ENDPOINT_MEASURE_2  & 0x3F,TX_USB_ENDPOINT_MEASURE_3  & 0x3F,TX_USB_ENDPOINT_MEASURE_4  & 0x3F}
#elif USB_TX_ENDPOINTS_NUMBER > 3
    #define USB_ENDPOINT_PORTS                      { TX_USB_ENDPOINT_CONTROL & 0x3F,TX_USB_ENDPOINT_MEASURE_1 & 0x3F,TX_USB_ENDPOINT_MEASURE_2  & 0x3F,TX_USB_ENDPOINT_MEASURE_3  & 0x3F}
#elif USB_TX_ENDPOINTS_NUMBER > 2
	#define USB_ENDPOINT_PORTS						{ TX_USB_ENDPOINT_CONTROL & 0x3F,TX_USB_ENDPOINT_MEASURE_1 & 0x3F,TX_USB_ENDPOINT_MEASURE_2  & 0x3F}
#elif  USB_TX_ENDPOINTS_NUMBER > 1
	#define USB_ENDPOINT_PORTS						{ TX_USB_ENDPOINT_CONTROL & 0x3F,TX_USB_ENDPOINT_MEASURE_1  & 0x3F}
#else
	#define USB_ENDPOINT_PORTS						{ TX_USB_ENDPOINT_CONTROL  & 0x3F}
#endif

#define CALIBRATION_SENSOR_COUNT		CALIBRATION_HEIGHT_SENSOR_COUNT * CALIBRATION_WIDTH_SENSOR_COUNT

#if (CALIBRATION_SENSOR_COUNT & 0x000007FF) != 0x00000000
    #define CALIBRATION_PAGE_ADDRESS(index)						CALIBRATION_ADDRESS + index * (USB_BUFFER_SIZE-8)
#else
    #define CALIBRATION_PAGE_ADDRESS(index)						CALIBRATION_ADDRESS + index * (USB_BUFFER_SIZE-8)
#endif


#define SPI_FLASH_COM_TYPE				0x01
#define SPI_FLASH_TX_TYPE				0x02
#define SPI_FLASH_RX_TYPE				0x03

#endif  /* AM3_BOARD_GENERIC_H_ */
